"""
ekavizmi.py — Korekcija ekavizama u ijekavski standard (BS/HR)
150+ zamjena u kategorijama.

Format: (pattern, zamjena, opis)
  - case-insensitive se primjenjuje u engineu
  - složeniji slučajevi imaju lookahead/lookbehind
"""

EKAVIZMI: list[tuple[str, str, str]] = [

    # ══════════════════════════════════════════════════════════════
    # A) GLAGOLI — RADNI GLAGOLSKI PRIDJEV (muški rod jednina)
    # ══════════════════════════════════════════════════════════════
    (r'\bhteo\b',       'htio',       'hteo→htio'),
    (r'\bsmeo\b',       'smio',       'smeo→smio'),
    (r'\bvideo\b(?!\s*(?:igr|zapis|kamer|klip|fajl|poruk|poziv|chat|konfer|snimak|format|sadržaj))',
                        'vidio',      'video→vidio (glagol, ne imenica)'),
    (r'\bsedeo\b',      'sjedio',     'sedeo→sjedio'),
    (r'\bleteo\b',      'letio',      'leteo→letio'),
    (r'\bpleteo\b',     'pletio',     'pleteo→pletio'),
    (r'\bdoneo\b',      'donio',      'doneo→donio'),
    (r'\bodneo\b',      'odnio',      'odneo→odnio'),
    (r'\bponeo\b',      'ponio',      'poneo→ponio'),
    (r'\bnaneo\b',      'nanio',      'naneo→nanio'),
    (r'\bzaveo\b',      'zavio',      'zaveo→zavio'),
    (r'\bpreveo\b',     'previo',     'preveo→previo'),
    (r'\buveo\b',       'uvio',       'uveo→uvio'),
    (r'\bnaveo\b',      'navio',      'naveo→navio'),
    (r'\bživeo\b',      'živio',      'živeo→živio'),
    (r'\bproživeo\b',   'proživio',   'proživeo→proživio'),
    (r'\bpreživeo\b',   'preživio',   'preživeo→preživio'),
    (r'\bsazreo\b',     'sazrio',     'sazreo→sazrio'),
    (r'\bzreo\b',       'zrio',       'zreo→zrio'),
    (r'\bgoreo\b',      'gorio',      'goreo→gorio'),
    (r'\bizgoreo\b',    'izgorio',    'izgoreo→izgorio'),
    (r'\btrpeo\b',      'trpio',      'trpeo→trpio'),
    (r'\bboleo\b',      'bolio',      'boleo→bolio'),
    (r'\bvoleo\b',      'volio',      'voleo→volio'),
    (r'\bzavladeo\b',   'zavladio',   'zavladeo→zavladio'),
    (r'\bvladeo\b',     'vladio',     'vladeo→vladio'),
    (r'\bpobedeo\b',    'pobijedio',  'pobedeo→pobijedio'),
    (r'\bpoveo\b',      'povio',      'poveo→povio'),
    (r'\bdoveo\b',      'dovio',      'doveo→dovio'),
    (r'\bizveo\b',      'izvio',      'izveo→izvio'),
    (r'\bosveo\b',      'osvio',      'osveo→osvio'),
    (r'\bpobegao\b',    'pobjegao',   'pobegao→pobjegao'),
    (r'\bbežao\b',      'bježao',     'bežao→bježao'),
    (r'\bsreo\b',       'sreo',       'sreo je isto u BS'),
    (r'\bstizao\b',     'stizao',     'stizao je isto'),
    (r'\btrčao\b',      'trčao',      'trčao je isto'),

    # ══════════════════════════════════════════════════════════════
    # B) GLAGOLI — ŽENSKI ROD I MNOŽINA RADNOG PRIDJEVA
    # ══════════════════════════════════════════════════════════════
    (r'\bvidela\b',     'vidjela',    'videla→vidjela'),
    (r'\bvideli\b',     'vidjeli',    'videli→vidjeli'),
    (r'\bvidelo\b',     'vidjelo',    'videlo→vidjelo'),
    (r'\bsedela\b',     'sjedila',    'sedela→sjedila'),
    (r'\bsedeli\b',     'sjedili',    'sedeli→sjedili'),
    (r'\bsedelo\b',     'sjedilo',    'sedelo→sjedilo'),
    (r'\bhtela\b',      'htjela',     'htela→htjela'),
    (r'\bhteli\b',      'htjeli',     'hteli→htjeli'),
    (r'\bsmela\b',      'smjela',     'smela→smjela'),
    (r'\bsmeli\b',      'smjeli',     'smeli→smjeli'),
    (r'\bdonela\b',     'donijela',   'donela→donijela'),
    (r'\bdoneli\b',     'donijeli',   'doneli→donijeli'),
    (r'\bletela\b',     'letjela',    'letela→letjela'),
    (r'\bleteli\b',     'letjeli',    'leteli→letjeli'),
    (r'\bživela\b',     'živjela',    'živela→živjela'),
    (r'\bživeli\b',     'živjeli',    'živeli→živjeli'),
    (r'\bpreživela\b',  'preživjela', 'preživela→preživjela'),
    (r'\bpreživeli\b',  'preživjeli', 'preživeli→preživjeli'),
    (r'\bvolela\b',     'voljela',    'volela→voljela'),
    (r'\bvoleli\b',     'voljeli',    'voleli→voljeli'),
    (r'\bgorela\b',     'gorjela',    'gorela→gorjela'),
    (r'\bgoreli\b',     'gorjeli',    'goreli→gorjeli'),
    (r'\btrpela\b',     'trpjela',    'trpela→trpjela'),
    (r'\btrpeli\b',     'trpjeli',    'trpeli→trpjeli'),
    (r'\bpobegla\b',    'pobjegla',   'pobegla→pobjegla'),
    (r'\bpobegli\b',    'pobjegli',   'pobegli→pobjegli'),
    (r'\bbežala\b',     'bježala',    'bežala→bježala'),
    (r'\bbežali\b',     'bježali',    'bežali→bježali'),
    (r'\bverovala\b',   'vjerovala',  'verovala→vjerovala'),
    (r'\bverovali\b',   'vjerovali',  'verovali→vjerovali'),
    (r'\bverovao\b',    'vjerovao',   'verovao→vjerovao'),
    (r'\bpevala\b',     'pjevala',    'pevala→pjevala'),
    (r'\bpevali\b',     'pjevali',    'pevali→pjevali'),
    (r'\bpobedila\b',   'pobijedila', 'pobedila→pobijedila'),
    (r'\bpobedili\b',   'pobijedili', 'pobedili→pobijedili'),

    # ══════════════════════════════════════════════════════════════
    # C) GLAGOLI — INFINITIV
    # ══════════════════════════════════════════════════════════════
    (r'\bdoneti\b',     'donijeti',   'doneti→donijeti'),
    (r'\bleteti\b',     'letjeti',    'leteti→letjeti'),
    (r'\bsedeti\b',     'sjediti',    'sedeti→sjediti'),
    (r'\bbežati\b',     'bježati',    'bežati→bježati'),
    (r'\bpevati\b',     'pjevati',    'pevati→pjevati'),
    (r'\bverovati\b',   'vjerovati',  'verovati→vjerovati'),
    (r'\bpobediti\b',   'pobijediti', 'pobediti→pobijediti'),
    (r'\bpobeđivati\b', 'pobjeđivati','pobeđivati→pobjeđivati'),
    (r'\bvoleti\b',     'voljeti',    'voleti→voljeti'),
    (r'\bgoreti\b',     'gorjeti',    'goreti→gorjeti'),
    (r'\btrpeti\b',     'trpjeti',    'trpeti→trpjeti'),
    (r'\bbrineti\b',    'brinutи',    'brineti→brinuti'),
    (r'\bsazreti\b',    'sazrijeti',  'sazreti→sazrijeti'),

    # ══════════════════════════════════════════════════════════════
    # D) GLAGOLI — PREZENT (sva lica)
    # ══════════════════════════════════════════════════════════════
    (r'\bsedim\b',      'sjedim',     'sedim→sjedim'),
    (r'\bsediš\b',      'sjediš',     'sediš→sjediš'),
    (r'\bsedi\b',       'sjedi',      'sedi→sjedi'),
    (r'\bsedimo\b',     'sjedimo',    'sedimo→sjedimo'),
    (r'\bsedite\b',     'sjedite',    'sedite→sjedite'),
    (r'\bsede\b',       'sjede',      'sede→sjede'),
    (r'\bbežim\b',      'bježim',     'bežim→bježim'),
    (r'\bbežiš\b',      'bježiš',     'bežiš→bježiš'),
    (r'\bbeži\b',       'bježi',      'beži→bježi'),
    (r'\bbežimo\b',     'bježimo',    'bežimo→bježimo'),
    (r'\bbežite\b',     'bježite',    'bežite→bježite'),
    (r'\bbеže\b',       'bježe',      'beže→bježe'),
    (r'\bbeže\b',       'bježe',      'beže→bježe'),
    (r'\bpevam\b',      'pjevam',     'pevam→pjevam'),
    (r'\bpevaš\b',      'pjevaš',     'pevaš→pjevaš'),
    (r'\bpeva\b',       'pjeva',      'peva→pjeva'),
    (r'\bpevamo\b',     'pjevamo',    'pevamo→pjevamo'),
    (r'\bpevate\b',     'pjevate',    'pevate→pjevate'),
    (r'\bpevaju\b',     'pjevaju',    'pevaju→pjevaju'),
    (r'\bverujem\b',    'vjerujem',   'verujem→vjerujem'),
    (r'\bveruješ\b',    'vjeruješ',   'veruješ→vjeruješ'),
    (r'\bveruje\b',     'vjeruje',    'veruje→vjeruje'),
    (r'\bverujemo\b',   'vjerujemo',  'verujemo→vjerujemo'),
    (r'\bverujete\b',   'vjerujete',  'verujete→vjerujete'),
    (r'\bveruju\b',     'vjeruju',    'veruju→vjeruju'),
    (r'\bvolim\b',      'volim',      'volim je isto u BS'),
    (r'\bpobedim\b',    'pobijedim',  'pobedim→pobijedim'),
    (r'\bpobediš\b',    'pobijediš',  'pobediš→pobijediš'),
    (r'\bpobedi\b',     'pobijedi',   'pobedi→pobijedi (prezent)'),
    (r'\bpobedimo\b',   'pobijedimo', 'pobedimo→pobijedimo'),
    (r'\bpobedite\b',   'pobijedite', 'pobedite→pobijedite'),
    (r'\bpobede\b',     'pobijede',   'pobede→pobijede'),

    # ══════════════════════════════════════════════════════════════
    # E) IMENICE — ČESTI EKAVIZMI
    # ══════════════════════════════════════════════════════════════
    (r'\bdete\b',       'dijete',     'dete→dijete'),
    (r'\bdeteta\b',     'djeteta',    'deteta→djeteta'),
    (r'\bdetetu\b',     'djetetu',    'detetu→djetetu'),
    (r'\bdetetom\b',    'djetetom',   'detetom→djetetom'),
    (r'\bdeca\b',       'djeca',      'deca→djeca'),
    (r'\bdeci\b',       'djeci',      'deci→djeci'),
    (r'\bdecom\b',      'djecom',     'decom→djecom'),
    (r'\bdečak\b',      'dječak',     'dečak→dječak'),
    (r'\bdečaka\b',     'dječaka',    'dečaka→dječaka'),
    (r'\bdečaku\b',     'dječaku',    'dečaku→dječaku'),
    (r'\bdečaci\b',     'dječaci',    'dečaci→dječaci'),
    (r'\bdečacima\b',   'dječacima',  'dečacima→dječacima'),
    (r'\bdevojka\b',    'djevojka',   'devojka→djevojka'),
    (r'\bdevojke\b',    'djevojke',   'devojke→djevojke'),
    (r'\bdevojci\b',    'djevojci',   'devojci→djevojci'),
    (r'\bdevojku\b',    'djevojku',   'devojku→djevojku'),
    (r'\bdevojkom\b',   'djevojkom',  'devojkom→djevojkom'),
    (r'\bdevojčica\b',  'djevojčica', 'devojčica→djevojčica'),
    (r'\bdevojčice\b',  'djevojčice', 'devojčice→djevojčice'),
    (r'\bdevojčici\b',  'djevojčici', 'devojčici→djevojčici'),
    (r'\bvreme\b',      'vrijeme',    'vreme→vrijeme'),
    (r'\bmesto\b',      'mjesto',     'mesto→mjesto'),
    (r'\bmesta\b',      'mjesta',     'mesta→mjesta'),
    (r'\bmestu\b',      'mjestu',     'mestu→mjestu'),
    (r'\bmestom\b',     'mjestom',    'mestom→mjestom'),
    (r'\bsvest\b',      'svijest',    'svest→svijest'),
    (r'\bsvesti\b',     'svijesti',   'svesti→svijesti'),
    (r'\bpesma\b',      'pjesma',     'pesma→pjesma'),
    (r'\bpesme\b',      'pjesme',     'pesme→pjesme'),
    (r'\bpesmi\b',      'pjesmi',     'pesmi→pjesmi'),
    (r'\bpesmom\b',     'pjesmom',    'pesmom→pjesmom'),
    (r'\bpesama\b',     'pjesama',    'pesama→pjesama'),
    (r'\bvetar\b',      'vjetar',     'vetar→vjetar'),
    (r'\bvetra\b',      'vjetra',     'vetra→vjetra'),
    (r'\bvetru\b',      'vjetru',     'vetru→vjetru'),
    (r'\bvetrom\b',     'vjetrom',    'vetrom→vjetrom'),
    (r'\breč\b',        'riječ',      'reč→riječ'),
    (r'\breči\b',       'riječi',     'reči→riječi'),
    (r'\brečima\b',     'riječima',   'rečima→riječima'),
    (r'\brečnik\b',     'rječnik',    'rečnik→rječnik'),
    (r'\brečnika\b',    'rječnika',   'rečnika→rječnika'),
    (r'\brečniku\b',    'rječniku',   'rečniku→rječniku'),
    (r'\bnedela\b',     'nedjelja',   'nedela→nedjelja'),
    (r'\bnedelja\b',    'nedjelja',   'nedelja→nedjelja'),
    (r'\bnedelje\b',    'nedjelje',   'nedelje→nedjelje'),
    (r'\bnedelju\b',    'nedjelju',   'nedelju→nedjelju'),
    (r'\bnedeljom\b',   'nedjeljom',  'nedeljom→nedjeljom'),
    (r'\bvera\b(?!\s*(?:Cruz|Wang|Lynn|Mae|Farmiga))',
                        'vjera',      'vera→vjera'),
    (r'\bvere\b',       'vjere',      'vere→vjere'),
    (r'\bveri\b',       'vjeri',      'veri→vjeri'),
    (r'\bverom\b',      'vjerom',     'verom→vjerom'),
    (r'\bpobeda\b',     'pobjeda',    'pobeda→pobjeda'),
    (r'\bpobede\b',     'pobjede',    'pobede→pobjede (imenica)'),
    (r'\bpobedi\b(?=\s+(?:u|na|od|nad|kroz|svim|svakom|njega|nje|njih))',
                        'pobjedi',    'pobedi→pobjedi (imenica, lokativ)'),
    (r'\bpobedom\b',    'pobjedom',   'pobedom→pobjedom'),
    (r'\bbeda\b',       'bijeda',     'beda→bijeda'),
    (r'\bbede\b',       'bijede',     'bede→bijede'),
    (r'\bbedi\b',       'bijedi',     'bedi→bijedi'),
    (r'\bbedom\b',      'bjedom',     'bedom→bjedom'),
    (r'\bpredeo\b',     'predjel',    'predeo→predjel'),
    (r'\bpredela\b',    'predjela',   'predela→predjela'),
    (r'\bpredelu\b',    'predjelu',   'predelu→predjelu'),
    (r'\bpredelom\b',   'prejelom',   'predelom→prejelom'),
    (r'\bsever\b',      'sjever',     'sever→sjever'),
    (r'\bsevera\b',     'sjevera',    'severa→sjevera'),
    (r'\bseveru\b',     'sjeveru',    'severu→sjeveru'),
    (r'\bpevač\b',      'pjevač',     'pevač→pjevač'),
    (r'\bpevača\b',     'pjevača',    'pevača→pjevača'),
    (r'\bpevačica\b',   'pjevačica',  'pevačica→pjevačica'),
    (r'\bpobednik\b',   'pobjednik',  'pobednik→pobjednik'),
    (r'\bpobednika\b',  'pobjednika', 'pobednika→pobjednika'),
    (r'\bpobednici\b',  'pobjednici', 'pobednici→pobjednici'),
    (r'\bpobednici\b',  'pobjednici', 'pobednici→pobjednici'),
    (r'\bpobedničk\w+', lambda m: 'pobjednički' if m.group(0).endswith('i') else 'pobjedničk' + m.group(0)[10:], 'pobednički→pobjednički'),
    (r'\bporažen\b',    'poražen',    'poražen je isto'),

    # ══════════════════════════════════════════════════════════════
    # F) PRIDJEVI
    # ══════════════════════════════════════════════════════════════
    (r'\bceo\b',        'cijeli',     'ceo→cijeli'),
    (r'\bcela\b',       'cijela',     'cela→cijela'),
    (r'\bceli\b',       'cijeli',     'celi→cijeli'),
    (r'\bcelo\b',       'cijelo',     'celo→cijelo'),
    (r'\bcelom\b',      'cijelom',    'celom→cijelom'),
    (r'\bcelog\b',      'cijelog',    'celog→cijelog'),
    (r'\bcelokupan\b',  'cjelokupan', 'celokupan→cjelokupan'),
    (r'\bcelokupna\b',  'cjelokupna', 'celokupna→cjelokupna'),
    (r'\bcelokupni\b',  'cjelokupni', 'celokupni→cjelokupni'),
    (r'\bsledeći\b',    'sljedeći',   'sledeći→sljedeći'),
    (r'\bsledeća\b',    'sljedeća',   'sledeća→sljedeća'),
    (r'\bsledeće\b',    'sljedeće',   'sledeće→sljedeće'),
    (r'\bsledećem\b',   'sljedećem',  'sledećem→sljedećem'),
    (r'\bsledećeg\b',   'sljedećeg',  'sledećeg→sljedećeg'),
    (r'\bsledećim\b',   'sljedećim',  'sledećim→sljedećim'),
    (r'\bverovatno\b',  'vjerovatno', 'verovatno→vjerovatno'),
    (r'\bverovatna\b',  'vjerovatna', 'verovatna→vjerovatna'),
    (r'\bverovatni\b',  'vjerovatni', 'verovatni→vjerovatni'),
    (r'\bverovatnoća\b','vjerovatnoća','verovatnoća→vjerovatnoća'),
    (r'\bneverovatno\b','nevjerovatno','neverovatno→nevjerovatno'),
    (r'\bneverovatna\b','nevjerovatna','neverovatna→nevjerovatna'),
    (r'\bneverovatni\b','nevjerovatni','neverovatni→nevjerovatni'),
    (r'\bneverovatan\b','nevjerovatan','neverovatan→nevjerovatan'),
    (r'\bbeo\b',        'bijel',      'beo→bijel'),
    (r'\bbela\b',       'bijela',     'bela→bijela'),
    (r'\bbeli\b',       'bijeli',     'beli→bijeli'),
    (r'\bbelo\b',       'bijelo',     'belo→bijelo'),
    (r'\bbelom\b',      'bijelom',    'belom→bijelom'),
    (r'\bbelog\b',      'bijelog',    'belog→bijelog'),
    (r'\bbedan\b',      'bijedan',    'bedan→bijedan'),
    (r'\bbedna\b',      'bijedna',    'bedna→bijedna'),
    (r'\bbedni\b',      'bijedni',    'bedni→bijedni'),
    (r'\bbedno\b',      'bijedno',    'bedno→bijedno'),
    (r'\bseverni\b',    'sjeverni',   'severni→sjeverni'),
    (r'\bseverna\b',    'sjeverna',   'severna→sjeverna'),
    (r'\bseverno\b',    'sjeverno',   'severno→sjeverno'),
    (r'\bsredan\b',     'sretan',     'sredan→sretan'),
    (r'\bsredna\b',     'sretna',     'sredna→sretna'),
    (r'\bnesredan\b',   'nesretan',   'nesredan→nesretan'),
    (r'\bnesredna\b',   'nesretna',   'nesredna→nesretna'),
    (r'\bnesredni\b',   'nesretni',   'nesredni→nesretni'),
    (r'\bsvetao\b',     'svijetao',   'svetao→svijetao'),
    (r'\bsvetla\b',     'svijetla',   'svetla→svijetla (pridev)'),
    (r'\bsvetli\b',     'svijetli',   'svetli→svijetli (pridev)'),
    (r'\bsvetlo\b',     'svijetlo',   'svetlo→svijetlo (pridev/prilog)'),
    (r'\btaman\b',      'taman',      'taman je isto'),

    # ══════════════════════════════════════════════════════════════
    # G) IMENICA "SVETLOST" I IZVEDENICE
    # ══════════════════════════════════════════════════════════════
    (r'\bsvetlost\b',   'svjetlost',  'svetlost→svjetlost'),
    (r'\bsvetlosti\b',  'svjetlosti', 'svetlosti→svjetlosti'),
    (r'\bsvetlošću\b',  'svjetlošću', 'svetlošću→svjetlošću'),
    (r'\bsvetiljka\b',  'svjetiljka', 'svetiljka→svjetiljka'),
    (r'\bsvetiljke\b',  'svjetiljke', 'svetiljke→svjetiljke'),
    (r'\bsvetlucati\b', 'svjetlucati','svetlucati→svjetlucati'),
    (r'\bsvetluca\b',   'svjetluca',  'svetluca→svjetluca'),

    # ══════════════════════════════════════════════════════════════
    # H) PRILOZI
    # ══════════════════════════════════════════════════════════════
    (r'\bovde\b',       'ovdje',      'ovde→ovdje'),
    (r'\bonde\b',       'ondje',      'onde→ondje'),
    (r'\bnegde\b',      'negdje',     'negde→negdje'),
    (r'\bnigde\b',      'nigdje',     'nigde→nigdje'),
    (r'\bigde\b',       'igdje',      'igde→igdje'),
    (r'\bsvugde\b',     'svugdje',    'svugde→svugdje'),
    (r'\buvek\b',       'uvijek',     'uvek→uvijek'),
    (r'\bposle\b',      'poslije',    'posle→poslije'),
    (r'\bpre\b(?=\s+(?:svega|nego|toga|svog|njega|nje|njih|nas|vas|mene|tebe|sebe|rata|revolucije|podne|dolaska|odlaska|završetka|početka|kraja|svake|svakog|ove|ovog|te|tog))',
                        'prije',      'pre→prije (prilog/prijedlog)'),

    # ══════════════════════════════════════════════════════════════
    # I) SLOŽENI PRIJEDLOŽNI IZRAZI
    # ══════════════════════════════════════════════════════════════
    (r'\bna mestu\b',       'na mjestu',        'na mestu→na mjestu'),
    (r'\bna licu mesta\b',  'na licu mjesta',   'na licu mesta→mjesta'),
    (r'\bna prvom mestu\b', 'na prvom mjestu',  'na prvom mestu→mjestu'),
    (r'\bnema mesta\b',     'nema mjesta',       'nema mesta→mjesta'),
    (r'\bima li mesta\b',   'ima li mjesta',     'ima li mesta→mjesta'),
    (r'\bu vreme\b',        'u vrijeme',         'u vreme→u vrijeme'),
    (r'\bu pravo vreme\b',  'u pravo vrijeme',   'u pravo vreme→vrijeme'),
    (r'\bs vremena na vreme\b', 's vremena na vrijeme', 's vremena na vreme'),
    (r'\bpre svega\b',      'prije svega',       'pre svega→prije svega'),
    (r'\bpre nego što\b',   'prije nego što',    'pre nego što→prije nego što'),
    (r'\bpre nego\b',       'prije nego',        'pre nego→prije nego'),
    (r'\bpre toga\b',       'prije toga',        'pre toga→prije toga'),
    (r'\bposle toga\b',     'poslije toga',      'posle toga→poslije toga'),
    (r'\bposle svega\b',    'poslije svega',     'posle svega→poslije svega'),
    (r'\bposle rata\b',     'poslije rata',      'posle rata→poslije rata'),
]

# Filtriraj: ukloni sve gdje je zamjena ista kao u opisu "je isto"
EKAVIZMI = [
    (pat, rep, opis)
    for (pat, rep, opis) in EKAVIZMI
    if 'je isto' not in opis and not callable(rep)
]
